// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMAF9jHSWDRIE4y2OiCIc8anowVhX9K_Q',
    appId: '1:604469097548:web:d1dec3c447a520304b30e9',
    messagingSenderId: '604469097548',
    projectId: 'arcade-aura',
    authDomain: 'arcade-aura.firebaseapp.com',
    databaseURL: 'https://arcade-aura-default-rtdb.firebaseio.com',
    storageBucket: 'arcade-aura.firebasestorage.app',
    measurementId: 'G-RS3MW8B3C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKd-SKrQC6HveXTnDXi1-Yl55AurXLAhQ',
    appId: '1:604469097548:android:34568a32fa3b31e34b30e9',
    messagingSenderId: '604469097548',
    projectId: 'arcade-aura',
    databaseURL: 'https://arcade-aura-default-rtdb.firebaseio.com',
    storageBucket: 'arcade-aura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjoDPp-RZw1Zb042Lh4CU-gxEZUt5RmAs',
    appId: '1:604469097548:ios:92e9bd3424a6825b4b30e9',
    messagingSenderId: '604469097548',
    projectId: 'arcade-aura',
    databaseURL: 'https://arcade-aura-default-rtdb.firebaseio.com',
    storageBucket: 'arcade-aura.firebasestorage.app',
    androidClientId: '604469097548-kp8fhgnrufbptgke5tjq6mh8p455n00h.apps.googleusercontent.com',
    iosClientId: '604469097548-vdmt8ukq91ujvcgo140rpgb4jue51f4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.arcadeAura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjoDPp-RZw1Zb042Lh4CU-gxEZUt5RmAs',
    appId: '1:604469097548:ios:92e9bd3424a6825b4b30e9',
    messagingSenderId: '604469097548',
    projectId: 'arcade-aura',
    databaseURL: 'https://arcade-aura-default-rtdb.firebaseio.com',
    storageBucket: 'arcade-aura.firebasestorage.app',
    androidClientId: '604469097548-kp8fhgnrufbptgke5tjq6mh8p455n00h.apps.googleusercontent.com',
    iosClientId: '604469097548-vdmt8ukq91ujvcgo140rpgb4jue51f4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.arcadeAura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMAF9jHSWDRIE4y2OiCIc8anowVhX9K_Q',
    appId: '1:604469097548:web:108ff366bd7af42b4b30e9',
    messagingSenderId: '604469097548',
    projectId: 'arcade-aura',
    authDomain: 'arcade-aura.firebaseapp.com',
    databaseURL: 'https://arcade-aura-default-rtdb.firebaseio.com',
    storageBucket: 'arcade-aura.firebasestorage.app',
    measurementId: 'G-QB0GNTPFP1',
  );
}
